- id: doi:10.1101/2024.10.10.617585
  type: paper
  description: Currently as a preprint on BioRxiv.
  image: images/Fig-Bat-paper.png

- id: doi:10.1038/s41467-024-47658-x
  type: paper
  image: images/nature-communications-logo.png
  
- id: doi:10.1242/dev.201562
  type: paper
  image: images/Fig-Sall1-paper.png

- id: doi:10.1002/jez.b.23142
  type: paper
  image: images/Fig-CellAdhesion-paper.png

- id: doi:10.1101/2023.03.22.533123
  type: paper
  description: Currently as a preprint on BioRxiv.
  image: images/BioRxiv_logo.png

- id: doi:10.1101/2022.10.28.514220
  type: paper
  description: Currently as a preprint on BioRxiv.
  image: images/BioRxiv_logo.png

