- id: doi:10.1016/j.tig.2016.01.003
  type: paper
  image: images/breaking_tads.png

- id: doi:10.1038/s41586-023-05868-1 
  type: paper
  image: images/skate.png
  
- id: doi:10.1038/s41576-018-0007-0 
  type: paper
  image: images/structural_variation.png

- id: doi:10.1038/s41588-018-0098-8 
  type: paper
  image: images/polymer_physics.png

- id: doi:10.1038/ng.3939
  type: paper
  image: images/indian_hedgehog.png

- id: doi:10.1016/j.cell.2015.04.004 
  type: paper
  image: images/disruptions.png
  
- id: 10.1016/j.celrep.2015.01.016 
  type: paper
  image: images/engeneering.png
