- id: doi:10.1016/j.tig.2016.01.003
  type: paper
  image: images/breaking_tads.jpg

- id: doi:10.1038/s41586-023-05868-1 
  type: paper
  image: images/skate3.jpg
  
- id: doi:10.1038/s41576-018-0007-0 
  type: paper
  image: images/structural_variation.jpg

- id: doi:10.1038/s41588-018-0098-8 
  type: paper
  image: images/polymer_physics.png

- id: doi:10.1038/ng.3939
  type: paper
  image: images/indian_hedgehog.jpg

- id: doi:10.1016/j.cell.2015.04.004 
  type: paper
  image: images/disruptions.png
  
- id: doi:10.1016/j.celrep.2015.01.016 
  type: paper
  image: images/engineering.jpg

- id: doi:10.1038/s41467-024-47658-x 
  type: paper
  image: images/miRNA.jpg

- id: doi:10.1073/pnas.2413191121
  type: paper
  image: images/trachemys.png

- id: doi:10.1016/j.gde.2022.102019 
  type: paper
  image: images/evolution3D

- id: doi:10.1038/s41588-022-01117-9
  type: paper
  image: images/anania.jpg

- id: doi:10.1126/science.aaz2582  
  type: paper
  image: images/molegenome.png

- id: doi:10.1101/2022.11.18.516861
  type: paper
  description: Currently as a preprint on BioRxiv.
  image: images/biorxiv.png
